name: deploy-live

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-live:
    runs-on: ubuntu-latest
    steps:
      - name: get latest code
        uses: actions/checkout@v4
      - name: install pnpm
        uses: pnpm/action-setup@v4
      - name: install node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
      - name: install dependencies
        run: pnpm install --frozen-lockfile
      - name: build app
        run: pnpm build
      - name: sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          local-dir: ./dist/
          protocol: ftps
          server: web15.greensta.de
          username: gsi_10556_1_happa-berlin.com
          password: ${{ secrets.FTP_PASSWORD }}
